### ISSUE TITLE
Can't compile with Coin

### ISSUE THREAD

**Issue by bejota** [TheHubbit/PyInventor#5]
Hello,
I am trying to compile with Coin which I have installed from your source. The Coin classes SbMatrix and SoForeignFileKit are not compatible. Thanks for any assistance.

System specs:
- CentOS release 6.3
-  GNU/Linux  2.6.32-279.22.1.el6.x86_64
- gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC)

From setup.py:
# Coin3D paths
oivincpath = '/usr/local/include'
oivlibpath = '/usr/local/lib'
oivlibname = 'COIN'

gcc errors:
>>: python3 ./setup.py install
running install
running build
running build_py
running build_ext
building 'inventor' extension
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python3.3/site-packages/numpy/numarray/include -I/usr/local/lib/python3.3/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/include/python3.3m -c src/PyInventor.cpp -o build/temp.linux-x86_64-3.3/src/PyInventor.o -DCOIN_DLL
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
src/PyInventor.cpp: In function 'PyObject* iv_write(PyObject*, PyObject*, PyObject*)':
src/PyInventor.cpp:181: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:181: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp: In function 'PyObject* iv_search(PyObject*, PyObject*, PyObject*)':
src/PyInventor.cpp:231: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:231: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:231: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:231: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:231: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:231: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp: In function 'PyObject* iv_pick(PyObject*, PyObject*, PyObject*)':
src/PyInventor.cpp:313: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:313: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:313: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:313: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:313: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:313: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:313: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:313: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:313: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:313: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp: In function 'PyObject* iv_image(PyObject*, PyObject*, PyObject*)':
src/PyInventor.cpp:411: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:411: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:411: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:411: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:411: warning: deprecated conversion from string constant to 'char*'
src/PyInventor.cpp:411: warning: deprecated conversion from string constant to 'char*'
/usr/local/lib/python3.3/site-packages/numpy/core/include/numpy/__multiarray_api.h: At global scope:
/usr/local/lib/python3.3/site-packages/numpy/core/include/numpy/__multiarray_api.h:1448: warning: 'int _import_array()' defined but not used
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python3.3/site-packages/numpy/numarray/include -I/usr/local/lib/python3.3/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/include/python3.3m -c src/PySceneManager.cpp -o build/temp.linux-x86_64-3.3/src/PySceneManager.o -DCOIN_DLL
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
src/PySceneManager.cpp:52: warning: ignoring #pragma warning
src/PySceneManager.cpp:53: warning: ignoring #pragma warning
src/PySceneManager.cpp: In static member function 'static PyTypeObject* PySceneManager::getType()':
src/PySceneManager.cpp:76: warning: deprecated conversion from string constant to 'char*'
src/PySceneManager.cpp:76: warning: deprecated conversion from string constant to 'char*'
src/PySceneManager.cpp:76: warning: deprecated conversion from string constant to 'char*'
src/PySceneManager.cpp:76: warning: deprecated conversion from string constant to 'char*'
src/PySceneManager.cpp:76: warning: deprecated conversion from string constant to 'char*'
src/PySceneManager.cpp:76: warning: deprecated conversion from string constant to 'char*'
src/PySceneManager.cpp: In static member function 'static int PySceneManager::tp_init(PySceneManager::Object*, PyObject*, PyObject*)':
src/PySceneManager.cpp:246: warning: deprecated conversion from string constant to 'char*'
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python3.3/site-packages/numpy/numarray/include -I/usr/local/lib/python3.3/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/include/python3.3m -c src/PySceneObject.cpp -o build/temp.linux-x86_64-3.3/src/PySceneObject.o -DCOIN_DLL
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
src/PySceneObject.cpp:34: warning: ignoring #pragma warning
src/PySceneObject.cpp:35: warning: ignoring #pragma warning
src/PySceneObject.cpp:36: warning: ignoring #pragma warning
src/PySceneObject.cpp: In function 'void inventorErrorCallback(const SoError*, void*)':
src/PySceneObject.cpp:145: warning: enumeration value 'ERROR' not handled in switch
src/PySceneObject.cpp: In static member function 'static PyTypeObject* PySceneObject::getNodeType()':
src/PySceneObject.cpp:366: warning: missing braces around initializer for 'PySequenceMethods'
src/PySceneObject.cpp:373: warning: missing braces around initializer for 'PyMappingMethods'
src/PySceneObject.cpp: In static member function 'static int PySceneObject::tp_init(PySceneObject::Object*, PyObject*, PyObject*)':
src/PySceneObject.cpp:624: warning: deprecated conversion from string constant to 'char*'
src/PySceneObject.cpp:624: warning: deprecated conversion from string constant to 'char*'
src/PySceneObject.cpp:624: warning: deprecated conversion from string constant to 'char*'
src/PySceneObject.cpp:624: warning: deprecated conversion from string constant to 'char*'
src/PySceneObject.cpp: In static member function 'static int PySceneObject::tp_init2(PySceneObject::Object*, PyObject*, PyObject*)':
src/PySceneObject.cpp:747: warning: deprecated conversion from string constant to 'char*'
src/PySceneObject.cpp:747: warning: deprecated conversion from string constant to 'char*'
src/PySceneObject.cpp:747: warning: deprecated conversion from string constant to 'char*'
src/PySceneObject.cpp: In static member function 'static int PySceneObject::setField(SoField*, PyObject*)':
src/PySceneObject.cpp:1171: warning: comparison between signed and unsigned integer expressions
src/PySceneObject.cpp:1180: warning: comparison between signed and unsigned integer expressions
src/PySceneObject.cpp:1192: warning: comparison between signed and unsigned integer expressions
src/PySceneObject.cpp:1228: warning: comparison between signed and unsigned integer expressions
src/PySceneObject.cpp:1272: error: no matching function for call to 'SbMatrix::setValue(float [16])'
/usr/local/include/Inventor/SbMatrix.h:52: note: candidates are: void SbMatrix::setValue(const float (&)[4][4])
/usr/local/include/Inventor/SbMatrix.h:53: note:                 void SbMatrix::setValue(const SbDPMatrix&)
src/PySceneObject.cpp:1294: error: no matching function for call to 'SbMatrix::setValue(float*)'
/usr/local/include/Inventor/SbMatrix.h:52: note: candidates are: void SbMatrix::setValue(const float (&)[4][4])
/usr/local/include/Inventor/SbMatrix.h:53: note:                 void SbMatrix::setValue(const SbDPMatrix&)
src/PySceneObject.cpp:1294: error: no matching function for call to 'SbMatrix::setValue(float*)'
/usr/local/include/Inventor/SbMatrix.h:52: note: candidates are: void SbMatrix::setValue(const float (&)[4][4])
/usr/local/include/Inventor/SbMatrix.h:53: note:                 void SbMatrix::setValue(const SbDPMatrix&)
src/PySceneObject.cpp: In static member function 'static PyObject* PySceneObject::tp_getattro(PySceneObject::Object*, PyObject*)':
src/PySceneObject.cpp:1349: error: 'class SoForeignFileKit' has no member named 'convert'
error: command 'gcc' failed with exit status 1

**Comment by TheHubbit** [comment]
Please try again with latest Coin source (from CMake branch). I'm unable to reproduce this issue on OS X and Windows. Unfortunately I don't have a Linux box.

**Comment by TheHubbit** [comment]
I've configured Linux builds with gcc and clang on Travis. Maybe that helps: https://travis-ci.org/TheHubbit/PyInventor/builds/232166880
