### ISSUE TITLE
no match for ‘operator<’    Ubuntu 18.04

### ISSUE THREAD

**Issue by sildeag** [TheHubbit/PyInventor#8]
`src/PyInventor.cpp:78:76:   required from here
/usr/include/c++/7/bits/stl_function.h:386:20: error: no match for ‘operator<’ (operand types are ‘const SbName’ and ‘const SbName’)`

**Comment by sildeag** [comment]
I've looked into this issue and uncovered differences between `SbString.h` in various Open Inventor APIs.  It would be helpful for me to know which Open Inventor toolkit are you using and whether it is available for download?  I struggled building `libFL` using `inventor-2.1.5-10-21` available on `Ubuntu 18.04`

**Comment by TheHubbit** [comment]
I’m using the latest Coin library (build from source, see Coin3D on Bitbucket) but also tested with FEI Open Inventor a while ago (now Thermo Fisher Scientific). I can change the map from SbName to std::string, which should fix the issue. However, there might be other compiler errors after this one is fixed.

**Comment by sildeag** [comment]
Thanks.
